export { default as Drawer } from './Drawer/Drawer'
export { default as Header } from './Header/Header'
export { default as Card } from './Card/Card'
export { default as Skeleton } from './Skeleton/Skeleton'
export { default as SimpleSlider } from './SimpleSlider/SimpleSlider'
export { default as Home } from '../pages/Home/Home'
export { default as Favorites } from '../pages/Favorites/Favorites'
export { default as Orders } from '../pages/Orders/Orders'
